### ISSUE TITLE
after finishing 360 drag it is trying load url 

### ISSUE THREAD

**Issue by praveenwala** [mediamanDE/three-sixty#14]
ImageLoader.prototype.load = function (url) {
        var _this = this;
        return new Promise(function (resolve) {
            if (_this.cache.hasOwnProperty(url)) {
                return resolve(_this.cache[url]);
            }
            var image = new Image();
            image.onload = function () {
                _this.cache[url] = image;
                resolve(image);
            };
            image.src = url;
        });
    };
    return ImageLoader;

i think in this function it should check for the url it getting. when it is undefined it is showing me error like this in screen shot,
![screen shot 2018-03-30 at 5 48 27 pm](https://user-images.githubusercontent.com/5037140/38139040-5f892506-344b-11e8-874c-20ada7344ffc.png)

**Comment by R4c00n** [comment]
Hello @praveenwala,
thanks for reporting this issue. I will have a look at it.
