### ISSUE TITLE
ERROR Error: "Uncaught (in promise): TypeError: _this.images.forEach is not a function

### ISSUE THREAD

**Issue by Cresusking** [mediamanDE/three-sixty#18]
I try to use @mediaman\angular-three-sixty module as it's describing here https://www.npmjs.com/package/@mediaman/angular-three-sixty . But a got errors below. Please could you help me. Thanks.

ERROR Error: "Uncaught (in promise): TypeError: _this.images.forEach is not a function
./node_modules/@mediaman/three-sixty/dist/three-sixty.es5.js/ThreeSixty.prototype.preload/<@http://localhost:4210/vendor.js:76217:13
ZoneAwarePromise@http://localhost:4210/polyfills.js:3213:29
./node_modules/@mediaman/three-sixty/dist/three-sixty.es5.js/ThreeSixty.prototype.preload@http://localhost:4210/vendor.js:76199:16
./node_modules/@mediaman/angular-three-sixty/esm5/angular-three-sixty.js/ThreeSixtyComponent.prototype.preloadImages@http://localhost:4210/vendor.js:75962:13
./node_modules/@mediaman/angular-three-sixty/esm5/angular-three-sixty.js/ThreeSixtyComponent.prototype.ngOnInit@http://localhost:4210/vendor.js:75925:9
checkAndUpdateDirectiveInline@http://localhost:4210/vendor.js:44999:9
checkAndUpdateNodeInline@http://localhost:4210/vendor.js:46263:20
checkAndUpdateNode@http://localhost:4210/vendor.js:46225:16
debugCheckAndUpdateNode@http://localhost:4210/vendor.js:46858:19
debugCheckDirectivesFn@http://localhost:4210/vendor.js:46818:13
View_Viewer360Component_0/<@ng:///AppModule/Viewer360Component.ngfactory.js:19:5
debugUpdateDirectives@http://localhost:4210/vendor.js:46810:12
checkAndUpdateView@http://localhost:4210/vendor.js:46207:5
callViewAction@http://localhost:4210/vendor.js:46448:21
execComponentViewsAction@http://localhost:4210/vendor.js:46390:13
checkAndUpdateView@http://localhost:4210/vendor.js:46213:5
callViewAction@http://localhost:4210/vendor.js:46448:21
execComponentViewsAction@http://localhost:4210/vendor.js:46390:13
checkAndUpdateView@http://localhost:4210/vendor.js:46213:5
callWithDebugContext@http://localhost:4210/vendor.js:47100:22
debugCheckAndUpdateView@http://localhost:4210/vendor.js:46778:12
./node_modules/@angular/core/fesm5/core.js/ViewRef_.prototype.detectChanges@http://localhost:4210/vendor.js:44594:13
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick/<@http://localhost:4210/vendor.js:40471:58
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick@http://localhost:4210/vendor.js:40471:13
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype._loadComponent@http://localhost:4210/vendor.js:40505:9
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.bootstrap@http://localhost:4210/vendor.js:40447:9
./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype._moduleDoBootstrap/<@http://localhost:4210/vendor.js:40248:74
./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype._moduleDoBootstrap@http://localhost:4210/vendor.js:40248:13
./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype.bootstrapModuleFactory/</</<@http://localhost:4210/vendor.js:40214:21
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4210/polyfills.js:2710:17
onInvoke@http://localhost:4210/vendor.js:39714:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4210/polyfills.js:2709:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:4210/polyfills.js:2460:24
scheduleResolveOrReject/<@http://localhost:4210/polyfills.js:3194:29
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4210/polyfills.js:2743:17
onInvokeTask@http://localhost:4210/vendor.js:39705:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4210/polyfills.js:2742:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4210/polyfills.js:2510:28
drainMicroTaskQueue@http://localhost:4210/polyfills.js:2917:25
"
resolvePromisehttp://localhost:4210/polyfills.js:3136:31resolvePromisehttp://localhost:4210/polyfills.js:3093:17scheduleResolveOrRejecthttp://localhost:4210/polyfills.js:3195:17invokeTaskhttp://localhost:4210/polyfills.js:2743:17onInvokeTaskhttp://localhost:4210/vendor.js:39705:24invokeTaskhttp://localhost:4210/polyfills.js:2742:17runTaskhttp://localhost:4210/polyfills.js:2510:28drainMicroTaskQueuehttp://localhost:4210/polyfills.js:2917:25 core.js:1624
defaultErrorLogger
core.js:1624
./node_modules/@angular/core/fesm5/core.js/ErrorHandler.prototype.handleError
core.js:1670
next
core.js:4252:109
./node_modules/@angular/core/fesm5/core.js/EventEmitter.prototype.subscribe/schedulerFn<
core.js:3488:34
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub
Subscriber.js:195
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.next
Subscriber.js:133
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._next
Subscriber.js:77
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next
Subscriber.js:54
./node_modules/rxjs/_esm5/internal/Subject.js/Subject.prototype.next
Subject.js:47
./node_modules/@angular/core/fesm5/core.js/EventEmitter.prototype.emit
core.js:3480:52
onHandleError/<
core.js:3779:48
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
zone.js:388
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run
zone.js:138
./node_modules/@angular/core/fesm5/core.js/NgZone.prototype.runOutsideAngular
core.js:3716
onHandleError
core.js:3779
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.handleError
zone.js:392
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runGuarded
zone.js:154
_loop_1
zone.js:677
./node_modules/zone.js/dist/zone.js/</</api.microtaskDrainDone
zone.js:686
drainMicroTaskQueue
zone.js:602

**Comment by R4c00n** [comment]
Hallo @Cresusking,
can you please post a snippet of how you are using our library?

**Comment by Pupskuchen** [comment]
Timeout
